eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: https://erp-eureka.herokuapp.com/eureka/
  instance:
    hostname: erp-eureka.herokuapp.com
    nonSecurePort: 80
logging:
  file:
    name: C:\logs\springboot.log
  level:
    root: INFO
    tn:
      esprit:
        repository: INFO
        service: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %-5level - %logger{36} - %msg%n'
server:
  port: 8082
spring:
  application:
    name: commande-microservice
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster1.h0jm2.mongodb.net/commande-microservice?retryWrites=true&w=majority
  profile: heroku
